# Generated by Django 4.1.5 on 2023-04-20 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Matches",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
    ]
